export function generateConfigFromTicket(ticket: string) {
  // Future: use Gemini here
  return {
    experimentName: `AutoGenerated-${Date.now()}`,
    description: `Generated from ticket ${ticket}`
  };
}
